/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ConvertOptions {
  /** JPEG quality (1-100, default 85) */
  quality?: number
}
/** Convert a HEIF/HEIC buffer to JPEG. */
export declare function heifToJpeg(input: Uint8Array, options?: ConvertOptions | undefined | null): Promise<Buffer>
